name: Continuous Integration with GitHub Actions

on:
  push:
    branches: 
      - 22_DockerizandoAplicacao
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven

    - name: Build Application JAR
      run: mvn clean package

    - name: Docker Compose Build
      run: docker compose build

    - name: Push to Docker Hub Container Regristry
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/rest-with-spring-boot-erudio:latest ${{ secrets.DOCKERHUB_USERNAME }}/rest-with-spring-boot-erudio:${{ github.run_id }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/rest-with-spring-boot-erudio:${{ github.run_id }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/rest-with-spring-boot-erudio:latest
